name: Localize Application Content

on:
  push:
    branches:
      - main # Or your default branch

permissions:
  contents: write
  pull-requests: write

jobs:
  localize:
    runs-on:  ubuntu-latest
    steps:
      - name: Run Locawise Localization
        uses: aemresafak/locawise-action@v1 # Use the latest version
        with:
          vertex-ai-service-account-key-base64: ${{ secrets.VERTEX_AI_SERVICE_ACCOUNT_KEY_BASE64 }} 
          source-lang-code: 'en'
          file-name-pattern: 'values-{language}/strings.xml'
          target-lang-codes: 'es,fr,de,it,tr,ja' # Comma-separated target languages
          localization-root-path: 'app/src/main/res/'

          context: |
            You are translating for "ProduceNow", a productivity application for creative professionals.
            Our users are designers, writers, and artists.
          glossary: |
            Project: A user's main workspace.
            Canvas: The area where users create their work.
            Export: The action of saving work to a file.
          tone: Be as polite as possible while also being friendly

          llm-model: 'gemini-2.0-flash'
          llm-location: 'us-central1' 

      - name: Get commit info
        id: commit-info
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
          COMMIT_MSG=$(git log -1 --pretty=%s | tr -d '\n')
          echo "commit_message=$COMMIT_MSG" >> $GITHUB_OUTPUT
        shell: bash

    # Feel free to change any part of the pull request!
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "[Bot] Update localization files from commit ${{ steps.commit-info.outputs.sha_short }}"
          title: "[Bot] Localization Update (${{ steps.commit-info.outputs.sha_short }})"
          body: |
            🤖 This PR was automatically created by the locawise workflow.
            Localization files have been updated from commit ${{ steps.commit-info.outputs.sha_short }}.
            Original commit message: "${{ steps.commit-info.outputs.commit_message }}"
          branch: localization-${{ steps.commit-info.outputs.sha_short }}
          base: main # Or your default branch
          labels: automated-pr, bot, localization
